version: '3.4'

services:

  customerdb:
    container_name: customerdb
    environment:
       - POSTGRES_USER=admin
       - POSTGRES_PASSWORD=admin1234
       - POSTGRES_DB=CustomerDB
    restart: always
    ports:
      - "5445:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data/
  csharp.crud.api:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    ports:
      - "7000:80"
